# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 11:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import postbar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TKclassTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classTagName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TKpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('attachment', models.FileField(null=True, upload_to=postbar.models.postAttPath)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('classTag', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=100)),
                ('numClick', models.IntegerField(default=0)),
                ('numResp', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('coin', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TKpostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=postbar.models.postImgPath)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postbar.TKpost')),
            ],
        ),
        migrations.CreateModel(
            name='TKrespImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=postbar.models.respImgPath)),
            ],
        ),
        migrations.CreateModel(
            name='TKresponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respType', models.SmallIntegerField(default=0)),
                ('content', models.CharField(max_length=400)),
                ('attachment', models.FileField(null=True, upload_to=postbar.models.respAttPath)),
                ('respId', models.IntegerField()),
                ('hostId', models.IntegerField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postbar.TKpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TKupvoteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvoteType', models.SmallIntegerField(default=0)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postbar.TKpost')),
                ('resp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postbar.TKresponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TKuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('img', models.ImageField(default='/static/images/mengbi.jpg', upload_to=postbar.models.user_directory_path)),
                ('pwdQuestion', models.CharField(max_length=100)),
                ('pwdAnswer', models.CharField(max_length=100)),
                ('numPost', models.IntegerField(default=0)),
                ('numScore', models.IntegerField(default=0)),
                ('numCoin', models.IntegerField(default=0)),
                ('usrStatus', models.SmallIntegerField(default=0)),
                ('usrType', models.SmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tkrespimage',
            name='resp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postbar.TKresponse'),
        ),
    ]
